#!/usr/bin/python
# coding=utf-8
"""Derive everything downstream of ``ptk.SceneRecords`` -- and fail when it drifts.

``pythontk.SceneRecords`` is the one declaration of
every tool-authored scene record (key, scope, version, kind, owner, readers,
description).  Two things outside pythontk used to restate it by hand and
drifted within weeks (the owner doc's channel tables were missing seven
records when measured 2026-09-18):

1. **The records table in the owner doc.**  ``mayatk/docs/data_nodes.md``
   carries a marker-spliced region (``<!-- scene-records:begin -->`` ...
   ``<!-- scene-records:end -->``) rendered from ``SceneRecords.describe()``.
   Everything outside the markers is hand-written; a missing marker pair is
   refused rather than guessed.
2. **The Unity importers' channel list.**  ``unitytk``'s
   ``UnitytkSettings.cs`` names one import channel per record it reads
   (``Audio, // "audio_manifest" channel -> AudioEventController``).  That
   set must equal the deliverable records declared with the ``"unity"``
   consumer -- a record Unity reads but pythontk does not declare (or the
   reverse) is a contract nobody owns -- and each named importer's
   ``SUPPORTED_*VERSION`` must equal its record's declared version: Unity
   refuses a newer payload at import, which no DCC-free check would see.
3. **The two DCC producer tables.**  ``mtk.FbxUtils.PRODUCERS`` and
   ``btk.FbxUtils.PRODUCERS`` must name the same records, except the ones
   :data:`PRODUCER_DIVERGENCES` ledgers with a reason (read from source by
   AST, so neither DCC needs to be importable here).
4. **The WebXR runtime's records module.**  ``kernel/records.js`` in
   pythontk's preview (:data:`WEB_RECORDS`) is generated whole: every record a
   GLB publishes for the web (``RecordSpec.web``) with its keys and versions,
   and a JSDoc typedef for each declared manifest shape
   (``WebProjection.shape``), so the page's features read a manifest by the
   declaration and ``tsc --checkJs`` holds them to its fields.

Usage:
    python sync_scene_records.py            # rewrite the derived files (idempotent)
    python sync_scene_records.py --check    # exit 1 on drift or a channel/version mismatch
"""

import argparse
import json
import re
import sys
from pathlib import Path

# This file: _scripts/m3trik/scripts/sync_scene_records.py -> repo root is parents[2].
REPO_ROOT = Path(__file__).resolve().parents[2]
DOC = REPO_ROOT / "mayatk" / "docs" / "data_nodes.md"
UNITY_SETTINGS = REPO_ROOT / "unitytk" / "unitytk" / "templates" / "UnitytkSettings.cs"
WEB_RECORDS = (
    REPO_ROOT
    / "pythontk"
    / "pythontk"
    / "net_utils"
    / "preview"
    / "kernel"
    / "records.js"
)
BEGIN = "<!-- scene-records:begin -->"
END = "<!-- scene-records:end -->"
#: What every generated file opens with -- the reader's cue not to edit it.
GENERATED = (
    "GENERATED by m3trik/scripts/sync_scene_records.py from pythontk's "
    "SceneRecords -- do not edit; run the script after changing a declaration."
)

FBX_UTILS = {
    "mayatk": REPO_ROOT / "mayatk" / "mayatk" / "env_utils" / "fbx_utils.py",
    "blendertk": REPO_ROOT / "blendertk" / "blendertk" / "env_utils" / "fbx_utils.py",
}
#: Records one DCC produces and the other deliberately does not: spec attribute
#: name -> (the DCC that lacks it, why). Delete a row when the port lands.
PRODUCER_DIVERGENCES = {
    "AUDIO": ("blendertk", "the Blender audio panel is VSE-only; port pending"),
    "ARTICULATION": ("blendertk", "ArticulatedRig is mayatk-only; twin pending"),
}

#: ``Audio,      // "audio_manifest" channel -> AudioEventController``
_UNITY_CHANNEL = re.compile(
    r'//\s*"(?P<key>\w+)"\s+channel\b(?:[^\w\n]+(?P<reader>\w+))?'
)
#: ``const int SUPPORTED_SCHEMA_VERSION = 2;`` -- one per importer.
_UNITY_SUPPORTED = re.compile(r"\bconst\s+int\s+SUPPORTED_\w*VERSION\s*=\s*(\d+)")


def _records():
    """``SceneRecords`` from the sibling pythontk checkout (not an installed copy)."""
    checkout = str(REPO_ROOT / "pythontk")
    if checkout not in sys.path:
        sys.path.insert(0, checkout)
    from pythontk import SceneRecords

    return SceneRecords


#: How a record's ``Merge`` rule reads in the table's *Crosses* column.
MERGE_LABELS = {
    "derive": "re-derived",
    "own": "keeps its own",
    "union": "unites",
    "codec": "domain merge",
}


def render_table(records=None) -> str:
    """The generated region's body: one row per declared record.  *Crosses*
    is what another scene's copy becomes beside this one's (the record's
    ``Merge`` rule) and whether it rides a DCC hand-off (``portable``)."""
    records = records or _records()
    lines = [
        "| Record | Carrier | Version | Kind | Owner | Reads | Read by | Web | Crosses | Holds |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    names = {"private": "`data_internal`", "deliverable": "`data_export`"}
    for row in records.describe():
        holds = row["description"]
        if row["deprecated_by"]:
            holds += f" -- *legacy: superseded by `{row['deprecated_by']}`*"
        # `.get`: a pythontk that predates the crossing columns (the CI gate
        # runs against the siblings' pushed branches) must read as drift in
        # the rendered table, not as a traceback.
        merge = row.get("merge", "")
        crosses = MERGE_LABELS.get(merge, merge)
        if row.get("portable"):
            crosses += ", hand-off"
        # `.get` for the same reason as `merge` above.
        web = row.get("web")
        lines.append(
            "| `{key}` | {carrier} | {version} | {kind} | {owner} | {reads} | {consumers} | {web} | {crosses} | {holds} |".format(
                key=row["key"],
                carrier=names[row["scope"]],
                version=row["version"]
                if row["envelope"]
                else f"{row['version']} (bare)",
                kind=row["kind"],
                owner=row["owner"],
                reads=", ".join(f"`{k}`" for k in row["after"]) or "--",
                consumers=", ".join(row["consumers"]) or "--",
                web=f"`{web}`" if web else "--",
                crosses=crosses,
                holds=holds.replace("|", "/"),
            )
        )
    return "\n".join(lines)


def splice(text: str, body: str) -> str:
    """*text* with the marker region replaced by *body*; refuses a missing pair."""
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < 0 or end < start:
        raise ValueError(f"{DOC.name} has no '{BEGIN}' ... '{END}' region")
    return text[: start + len(BEGIN)] + "\n" + body + "\n" + text[end:]


def unity_reader(reader):
    """The template file of the importer *reader* names -- ``<reader>.cs``
    wherever it sits under ``templates/`` (a feature folder) -- or ``None``."""
    if not reader:
        return None
    found = sorted(UNITY_SETTINGS.parent.rglob(f"{reader}.cs"))
    return found[0] if len(found) == 1 else None


def unity_reader_version(reader):
    """The version *reader*'s importer accepts (its one ``SUPPORTED_*VERSION``
    in its ``<reader>.cs``), or ``None`` when that cannot be read."""
    path = unity_reader(reader)
    if path is None:
        return None
    found = _UNITY_SUPPORTED.findall(path.read_text(encoding="utf-8"))
    return int(found[0]) if len(found) == 1 else None


def unity_mismatch(records=None) -> dict:
    """``{"undeclared": [...], "unread": [...], "version": [...]}`` -- channels
    Unity reads that no record declares for it, records declared for Unity it
    does not read, and channels whose importer accepts another version than
    the record declares (as lines)."""
    records = records or _records()
    readers = {
        m["key"]: m["reader"]
        for m in _UNITY_CHANNEL.finditer(UNITY_SETTINGS.read_text(encoding="utf-8"))
    }
    specs = {s.key: s for s in records.deliverable() if "unity" in s.consumers}
    version = []
    for key in sorted(readers.keys() & specs.keys()):
        reader, declared = readers[key], specs[key].version
        accepts = unity_reader_version(reader)
        if accepts is None:
            version.append(
                f"{key}: no single SUPPORTED_*VERSION in the importer its channel"
                f" line names ({reader or 'none'})"
            )
        elif accepts != declared:
            version.append(
                f"{key}: declared v{declared}, {reader}.cs accepts v{accepts}"
            )
    return {
        "undeclared": sorted(readers.keys() - specs.keys()),
        "unread": sorted(specs.keys() - readers.keys()),
        "version": version,
    }


def producer_specs(path: Path) -> set:
    """The ``SceneRecords`` attribute names a ``FbxUtils.PRODUCERS`` table keys on."""
    import ast

    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        target = getattr(node, "target", None) or (
            node.targets[0] if isinstance(node, ast.Assign) and node.targets else None
        )
        if getattr(target, "id", None) != "PRODUCERS":
            continue
        value = getattr(node, "value", None)
        if isinstance(value, ast.Dict):
            return {k.attr for k in value.keys if isinstance(k, ast.Attribute)}
    raise ValueError(f"no PRODUCERS table in {path}")


def producer_parity() -> list:
    """Unledgered differences between the two DCC producer tables, as lines."""
    tables = {dcc: producer_specs(path) for dcc, path in FBX_UTILS.items()}
    problems = []
    for spec in sorted(set().union(*tables.values())):
        missing = [dcc for dcc, specs in tables.items() if spec not in specs]
        ledgered = PRODUCER_DIVERGENCES.get(spec, (None,))[0]
        for dcc in missing:
            if dcc != ledgered:
                problems.append(f"{dcc} does not produce SceneRecords.{spec}")
    for spec, (dcc, _why) in PRODUCER_DIVERGENCES.items():
        if spec in tables[dcc]:
            problems.append(f"stale ledger row: {dcc} now produces SceneRecords.{spec}")
    return problems


# ----------------------------------------------------- the web runtime's records
def _spec_names(records) -> dict:
    """``{id(spec): attribute}`` -- SceneRecords' own name for each declaration
    (``ARTICULATION``), the name a generated reader uses for it."""
    spec_type = type(records.SHOTS)
    return {id(v): k for k, v in vars(records).items() if isinstance(v, spec_type)}


def _plain(text: str) -> str:
    """A docstring sentence for another language's doc comment: RST's double
    backticks to single, whitespace to one space."""
    return " ".join(text.replace("``", "`").split())


def _wrap(text: str, width: int = 74) -> list:
    """*text* in lines of at most *width* characters, words whole."""
    lines, line = [], ""
    for word in text.split():
        if line and len(line) + 1 + len(word) > width:
            lines.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    return lines + [line] if line else lines


def jsdoc_type(node: dict) -> str:
    """The JSDoc type of a JSON Schema fragment (``SchemaSpec.json_schema``)."""
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in node:
        return "|".join(dict.fromkeys(jsdoc_type(n) for n in node["anyOf"]))
    if "enum" in node:
        return "|".join(
            f"'{v}'" if isinstance(v, str) else json.dumps(v) for v in node["enum"]
        )
    kind = node.get("type")
    if kind == "array":
        if "prefixItems" in node:
            return "[" + ", ".join(jsdoc_type(n) for n in node["prefixItems"]) + "]"
        item = jsdoc_type(node["items"]) if "items" in node else "*"
        return f"({item})[]" if "|" in item else f"{item}[]"
    if kind == "object":
        values = node.get("additionalProperties")
        return f"Object<string, {jsdoc_type(values)}>" if values else "object"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "*")


def render_typedef(name: str, schema: dict) -> list:
    """One JSDoc ``@typedef`` block for an object schema."""
    lines = ["/**"]
    lines += [f" * {line}" for line in _wrap(_plain(schema.get("description", "")))]
    lines.append(f" * @typedef {{object}} {name}")
    required = set(schema.get("required", ()))
    for key, node in schema.get("properties", {}).items():
        label = key if key in required else f"[{key}]"
        about = _plain(node.get("description", ""))
        lines.append(
            f" * @property {{{jsdoc_type(node)}}} {label}{' ' + about if about else ''}"
        )
    lines.append(" */")
    return lines


def render_records_js(records=None) -> str:
    """``kernel/records.js``: every record a GLB publishes for the web, and the
    JSDoc typedefs of each declared manifest shape (:data:`WEB_RECORDS`)."""
    records = records or _records()
    names = _spec_names(records)
    lines = ["/*", f"  {_wrap(GENERATED, 72)[0]}"]
    lines += [f"  {line}" for line in _wrap(GENERATED, 72)[1:]]
    lines += [
        "",
        "  The scene records a deliverable publishes for the glTF runtimes: each",
        "  record's key and schema version, the root-extras key its manifest ships",
        "  under and that manifest's own version -- and, where it is declared, the",
        "  manifest's shape. A feature reads a manifest by these, never by a",
        "  spelling of its own.",
        "*/",
        "",
        "/**",
        " * A scene record a GLB conversion publishes for the glTF runtimes.",
        " * @typedef {object} WebRecord",
        " * @property {string} key The record's channel on the `data_export` carrier.",
        " * @property {number} version The record's schema version.",
        " * @property {string} webKey The root-extras key its manifest ships under.",
        " * @property {number} webVersion The manifest's own schema version.",
        " */",
        "",
    ]
    shapes = []
    for spec in records.web_projected():
        lines += [
            f"/** `{spec.key}`, published as `{spec.web.key}`. @type {{Readonly<WebRecord>}} */",
            f"export const {names[id(spec)]} = Object.freeze({{ key: '{spec.key}', "
            f"version: {spec.version}, webKey: '{spec.web.key}', "
            f"webVersion: {spec.web.version} }});",
        ]
        shape = records.web_shape(spec)
        if shape is not None:
            shapes.append(shape)
    for shape in shapes:
        schema = shape.json_schema()
        lines += [
            "",
            f"/* {'-' * 12} the `{shape.__name__}` manifest, declared in pythontk {'-' * 12} */",
        ]
        lines += [""] + render_typedef(shape.__name__, schema)
        for name, node in schema.get("$defs", {}).items():
            lines += [""] + render_typedef(name, node)
    return "\n".join(lines) + "\n"


# ------------------------------------------------------ the C# record types
#: C# keywords a payload key could collide with (escaped as ``@key``).
CS_KEYWORDS = frozenset(
    "abstract as base bool break byte case catch char checked class const "
    "continue decimal default delegate do double else enum event explicit "
    "extern false finally fixed float for foreach goto if implicit in int "
    "interface internal is lock long namespace new null object operator out "
    "override params private protected public readonly ref return sbyte "
    "sealed short sizeof stackalloc static string struct switch this throw "
    "true try typeof uint ulong unchecked unsafe ushort using virtual void "
    "volatile while".split()
)
#: The namespace a record type's ``.meta`` GUID is derived in: one stable
#: GUID per record, whatever folder its reader sits in.
CS_GUID_NAMESPACE = "https://github.com/m3trik/unitytk/records/"


def _cs_name(def_name: str, root: str) -> str:
    """A declared shape's nested C# class name: the root itself is
    ``Payload``; another drops the family prefix the root's name gives
    (``ArticulationRecord`` -> ``Articulation``: ``ArticulationJoint`` is
    ``ArticulationRecord.Joint``)."""
    if def_name == root:
        return "Payload"
    family = root[: -len("Record")] if root.endswith("Record") else root
    rest = def_name[len(family) :] if def_name.startswith(family) else ""
    return rest if rest[:1].isupper() else def_name


def _cs_member(key: str, node: dict, root: str) -> tuple:
    """``(C# type, read expression over ``o``)`` of one payload key."""
    if "anyOf" in node:
        options = [n for n in node["anyOf"] if n.get("type") != "null"]
        node = options[0] if len(options) == 1 else {}
    if "$ref" in node:
        cls = _cs_name(node["$ref"].rsplit("/", 1)[-1], root)
        return cls, f'{cls}.Read(Wire.Get(o, "{key}"))'
    kind = node.get("type")
    if kind == "array":
        items = node.get("prefixItems") or [node.get("items", {})]
        if all(item.get("type") == "number" for item in items):
            return "double[]", f'Wire.Nums(o, "{key}")'
        item = items[0]
        if "$ref" in item:
            cls = _cs_name(item["$ref"].rsplit("/", 1)[-1], root)
            return f"List<{cls}>", f'Wire.Items(o, "{key}", {cls}.Read)'
        return "IList<object>", f'Wire.Get(o, "{key}") as IList<object>'
    simple = {
        "string": ("string", "Str"),
        "integer": ("int?", "Int"),
        "number": ("double?", "Num"),
        "boolean": ("bool?", "Bool"),
    }
    if kind in simple:
        cs, reader = simple[kind]
        return cs, f'Wire.{reader}(o, "{key}")'
    if kind == "object":
        return (
            "IDictionary<string, object>",
            f'Wire.Get(o, "{key}") as IDictionary<string, object>',
        )
    return "object", f'Wire.Get(o, "{key}")'


def _cs_summary(text: str, indent: str) -> list:
    """A ``/// <summary>`` block for *text* (escaped for XML)."""
    text = _plain(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    lines = _wrap(text, 92 - len(indent))
    if len(lines) <= 1:
        return [f"{indent}/// <summary>{text}</summary>"]
    return (
        [f"{indent}/// <summary>"]
        + [f"{indent}/// {line}" for line in lines]
        + [f"{indent}/// </summary>"]
    )


#: The generated readers' conversions -- the JSON tree's values as the fields'
#: types. A number converts the way the hand-written readers always did
#: (``Convert``, invariant culture), so a value that is not one fails loudly
#: rather than reading as null.
CS_WIRE = """\
// The JSON tree's values as the fields' types. A number converts the way the
// hand-written readers always did (Convert, invariant culture), so a value that
// is not one fails loudly rather than reading as null.
static class Wire
{
    public static object Get(IDictionary<string, object> o, string key)
        => o.TryGetValue(key, out var v) ? v : null;

    public static string Str(IDictionary<string, object> o, string key)
    {
        object v = Get(o, key);
        return v == null ? null : v as string ?? Convert.ToString(v, CultureInfo.InvariantCulture);
    }

    public static double? Num(IDictionary<string, object> o, string key)
    {
        object v = Get(o, key);
        return v == null ? (double?)null : Convert.ToDouble(v, CultureInfo.InvariantCulture);
    }

    public static int? Int(IDictionary<string, object> o, string key)
    {
        double? v = Num(o, key);
        return v.HasValue ? (int?)(int)v.Value : null;
    }

    public static bool? Bool(IDictionary<string, object> o, string key)
    {
        object v = Get(o, key);
        return v == null ? (bool?)null : Convert.ToBoolean(v, CultureInfo.InvariantCulture);
    }

    public static double[] Nums(IDictionary<string, object> o, string key)
    {
        if (!(Get(o, key) is IList<object> list)) return null;
        var items = new double[list.Count];
        for (int i = 0; i < list.Count; i++)
            items[i] = Convert.ToDouble(list[i], CultureInfo.InvariantCulture);
        return items;
    }

    public static List<T> Items<T>(IDictionary<string, object> o, string key, Func<object, T> read)
    {
        if (!(Get(o, key) is IList<object> list)) return null;
        var items = new List<T>(list.Count);
        foreach (object item in list) items.Add(read(item));
        return items;
    }
}
"""


def render_record_cs(spec, shape) -> str:
    """The C# types of record *spec*'s declared *shape*: one class per
    declared object, nested in ``<shape>.Shape`` of ``public static partial
    class <shape>``, whose other half -- the reader's policy: its channel, the
    versions it reads -- is hand-written beside it."""
    schema = shape.json_schema()
    root = shape.__name__
    objects = [(root, schema)] + list(schema.get("$defs", {}).items())
    about = (
        f"The `{spec.key}` record's payload as pythontk declares it ({root}): "
        "one class per declared object, a field per key. Read takes the parsed "
        "JSON tree -- an object as IDictionary<string, object>, an array as "
        "IList<object>, a number as double -- and reads the way a record reader "
        "must: a key left out, or null, reads as null; a key it does not declare "
        "is ignored; an entry of a list that is not an object reads as null in "
        "its place, so indices keep. Not JsonUtility, which cannot say null (a "
        "channel with no limit). The policy -- which versions are read, what a "
        "null means -- is the reader's own, in the hand-written half of this "
        "partial class."
    )
    lines = ["// <auto-generated>"]
    lines += [f"// {line}" for line in _wrap(GENERATED, 76)]
    lines += ["// </auto-generated>", "//"]
    lines += [f"// {line}" for line in _wrap(about, 76)]
    lines += [
        "using System;",
        "using System.Collections.Generic;",
        "using System.Globalization;",
        "",
        f"public static partial class {root}",
        "{",
        f"    /// <summary>The `{spec.key}` record's declared shape ({root}).</summary>",
        "    public static class Shape",
        "    {",
    ]
    for def_name, node in objects:
        cls = _cs_name(def_name, root)
        lines += _cs_summary(node.get("description", ""), "        ")
        lines += [f"        public sealed class {cls}", "        {"]
        members = []
        for key, prop in node.get("properties", {}).items():
            cs_type, read = _cs_member(key, prop, root)
            field = f"@{key}" if key in CS_KEYWORDS else key
            lines += _cs_summary(prop.get("description", ""), "            ")
            lines.append(f"            public {cs_type} {field};")
            members.append((field, read))
        lines += [
            "",
            "            /// <summary>One read off a parsed JSON value; null when it is not an object.</summary>",
            f"            public static {cls} Read(object value)",
            "            {",
            "                if (!(value is IDictionary<string, object> o)) return null;",
            f"                return new {cls}",
            "                {",
        ]
        lines += [f"                    {field} = {read}," for field, read in members]
        lines += ["                };", "            }", "        }", ""]
    lines += [f"        {line}" if line else "" for line in CS_WIRE.splitlines()]
    lines += ["    }", "}"]
    return "\n".join(lines) + "\n"


def record_cs_meta(spec) -> str:
    """The ``.meta`` a generated record type ships with: a GUID derived from
    the record's key alone, so regenerating -- or moving its reader to another
    folder -- never mints a new one (unitytk deploys every file with its own)."""
    import uuid

    guid = uuid.uuid5(uuid.NAMESPACE_URL, CS_GUID_NAMESPACE + spec.key).hex
    return (
        "fileFormatVersion: 2\n"
        f"guid: {guid}\n"
        "MonoImporter:\n"
        "  externalObjects: {}\n"
        "  serializedVersion: 2\n"
        "  defaultReferences: []\n"
        "  executionOrder: 0\n"
        "  icon: {instanceID: 0}\n"
        "  userData: \n"
        "  assetBundleName: \n"
        "  assetBundleVariant: \n"
    )


def record_cs_targets(records=None) -> list:
    """``[(spec, shape, .cs path)]``: every record Unity reads that declares
    its shape, written beside the importer its channel line names."""
    records = records or _records()
    readers = {
        m["key"]: m["reader"]
        for m in _UNITY_CHANNEL.finditer(UNITY_SETTINGS.read_text(encoding="utf-8"))
    }
    targets = []
    for spec in records.deliverable():
        shape = records.shape(spec)
        if shape is None or "unity" not in spec.consumers:
            continue
        reader = unity_reader(readers.get(spec.key))
        if reader is not None:
            targets.append((spec, shape, reader.parent / f"{shape.__name__}.g.cs"))
    return targets


def sync_text(path: Path, wanted: str, check: bool, what: str) -> bool:
    """Hold *path* to *wanted* (LF text; the file's own newline style is
    kept). Returns whether it drifted; writes the fix unless *check*."""
    raw = path.read_bytes().decode("utf-8") if path.is_file() else ""
    nl = "\r\n" if "\r\n" in raw else "\n"
    if raw.replace("\r\n", "\n") == wanted:
        return False
    if check:
        print(
            f"DRIFT: {path.relative_to(REPO_ROOT)} {what} is stale;"
            " run sync_scene_records.py"
        )
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(wanted.replace("\n", nl).encode("utf-8"))
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return False


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="exit 1 on drift")
    args = parser.parse_args(argv)

    records = _records()
    text = DOC.read_bytes().decode("utf-8").replace("\r\n", "\n")
    failed = sync_text(
        DOC, splice(text, render_table(records)), args.check, "records table"
    )
    failed |= sync_text(
        WEB_RECORDS, render_records_js(records), args.check, "web records module"
    )
    for spec, shape, path in record_cs_targets(records):
        failed |= sync_text(
            path, render_record_cs(spec, shape), args.check, "C# record types"
        )
        meta = path.with_name(path.name + ".meta")
        failed |= sync_text(
            meta, record_cs_meta(spec), args.check, "record types' .meta"
        )
    for problem in producer_parity():
        print(f"PRODUCERS: {problem}")
        failed = True
    mismatch = unity_mismatch(records)
    for kind, keys in mismatch.items():
        for key in keys:
            print(f"UNITY {kind.upper()}: {key}")
            failed = True
    if not failed:
        print(
            f"in sync: {len(records.all())} records, "
            f"{sum(1 for s in records.deliverable() if 'unity' in s.consumers)} read by Unity"
        )
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
